/**
 * Cross-language conformance vectors.
 *
 * The TypeScript, Swift and Kotlin emitters are generated by three DIFFERENT
 * protobuf compilers from the same telemetry.proto. Nothing structurally forces
 * them to agree, so agreement is pinned here: these vectors are the contract.
 *
 * `golden-vectors.json` holds hex-encoded canonical encodings. This suite
 * asserts the TS codec reproduces them byte-for-byte and decodes them back to
 * the expected domain values. The Swift/Kotlin test suites load the SAME file
 * and assert the same things (P4).
 *
 * Regenerate deliberately (never to paper over a diff):
 *   UPDATE_GOLDEN=1 pnpm --filter @livetrace/protocol test
 * A vector changing without a protocol version bump is a breaking-change bug.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { Decoder, Encoder } from '../src/codec.js';
import { FrameOpener, FrameSealer, importSessionKey } from '../src/crypto.js';
import type { LiveMetrics, RouteMeta, SessionHello } from '../src/types.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const GOLDEN_PATH = join(HERE, 'golden-vectors.json');
const UPDATE = process.env.UPDATE_GOLDEN === '1';

const T0 = 1_760_000_000_000;
const SESSION_ID = '3f2504e0-4f89-41d3-9a0c-0305e82c3301';
/** Fixed test key/salt — DETERMINISTIC TEST DATA ONLY, never a real session. */
const TEST_KEY = new Uint8Array(32).map((_, i) => (i * 7 + 13) & 0xff);
const TEST_SALT = new Uint8Array([0xde, 0xad, 0xbe, 0xef]);

const hex = (b: Uint8Array) =>
  Array.from(b, (x) => x.toString(16).padStart(2, '0')).join('');
const unhex = (s: string) =>
  new Uint8Array((s.match(/../g) ?? []).map((h) => parseInt(h, 16)));

// ───────────────────────── canonical fixtures ──────────────────────────────

const HELLO: SessionHello = {
  sessionId: SESSION_ID,
  t0EpochMs: T0,
  sport: 'trail_running',
  emitterAgent: 'livetrace-conformance/1.0.0',
  hasRoute: true,
  sampleHz: 1,
};

const TELEMETRY_FULL: LiveMetrics = {
  seq: 3600,
  timestamp: T0 + 3_600_000,
  position: { lat: 46.6204190, lon: 6.2143550, altM: 1402.5, hAccM: 4.25 },
  speedMps: 3.35,
  courseDeg: 187.5,
  heartRateBpm: 151,
  cadenceRpm: 172,
  powerW: 288,
  paceSecPerKm: 298.5,
  elevationGainM: 412,
  elevationLossM: 118.5,
  route: {
    distanceDoneM: 5321.5,
    distanceRemainingM: 12678.5,
    ascentRemainingM: 640.25,
    descentRemainingM: 810.75,
    etaEpochMs: T0 + 4_500_000,
    etaRemainingSec: 4458,
    fraction: 0.25,
    segIndex: 137,
    offRoute: false,
    crossTrackM: 6.75,
  },
  batteryPct: 78,
  sources: {
    position: 'phone-gps',
    heartRate: 'watch-broadcast',
    cadence: 'ble-sensor',
    power: 'ble-sensor',
  },
};

/** Southern + western hemisphere, no sensors — exercises sign handling. */
const TELEMETRY_SPARSE: LiveMetrics = {
  seq: 1,
  timestamp: T0 + 1000,
  position: { lat: -33.8688, lon: -151.2093, altM: -12.5, hAccM: null },
  speedMps: null,
  courseDeg: null,
  heartRateBpm: null,
  cadenceRpm: null,
  powerW: null,
  paceSecPerKm: null,
  elevationGainM: 0,
  elevationLossM: 0,
  route: null,
  batteryPct: null,
  sources: {
    position: 'phone-gps',
    heartRate: 'unknown',
    cadence: 'unknown',
    power: 'unknown',
  },
};

const ROUTE: RouteMeta = {
  routeId: 'route-conformance-1',
  name: 'Col de Balme',
  totalDistM: 18000,
  totalAscentM: 1200,
  totalDescentM: 1150,
  points: [
    { lat: 46.62, lon: 6.6, eleM: 1000 },
    { lat: 46.6205, lon: 6.6008, eleM: 1012.5 },
    { lat: 46.6211, lon: 6.6015, eleM: 1025 },
    { lat: 46.6218, lon: 6.6021, eleM: 1018.5 },
  ],
  bbox: { minLat: 46.62, minLon: 6.6, maxLat: 46.6218, maxLon: 6.6021 },
};

function buildVectors() {
  const enc = new Encoder(T0);
  return {
    _comment:
      'Canonical encodings for cross-language conformance (TS / Swift / Kotlin). ' +
      'Hex-encoded. Regenerate only with an intentional protocol change.',
    protocolVersion: 1,
    sessionId: SESSION_ID,
    t0EpochMs: T0,
    testKeyHex: hex(TEST_KEY),
    testSaltHex: hex(TEST_SALT),
    envelopes: {
      hello: hex(enc.hello(HELLO)),
      telemetryFull: hex(enc.telemetry(TELEMETRY_FULL)),
      telemetrySparse: hex(enc.telemetry(TELEMETRY_SPARSE)),
      route: hex(enc.route(ROUTE)),
      state: hex(enc.state({ transport: 'p2p-direct', viewerCount: 3, emitterLive: true })),
      heartbeat: hex(enc.heartbeat(3_600_000)),
      end: hex(enc.end({ reason: 'completed', detail: 'finished' })),
    },
  };
}

type Vectors = ReturnType<typeof buildVectors>;

function loadVectors(): Vectors {
  const current = buildVectors();
  if (UPDATE || !existsSync(GOLDEN_PATH)) {
    writeFileSync(GOLDEN_PATH, `${JSON.stringify(current, null, 2)}\n`);
    return current;
  }
  return JSON.parse(readFileSync(GOLDEN_PATH, 'utf8')) as Vectors;
}

const golden = loadVectors();

// ───────────────────────────── the contract ────────────────────────────────

describe('golden vectors — byte-for-byte encoding stability', () => {
  const enc = new Encoder(T0);

  it('protocol version and session constants are pinned', () => {
    expect(golden.protocolVersion).toBe(1);
    expect(golden.sessionId).toBe(SESSION_ID);
    expect(golden.t0EpochMs).toBe(T0);
  });

  it.each([
    ['hello', () => enc.hello(HELLO)],
    ['telemetryFull', () => enc.telemetry(TELEMETRY_FULL)],
    ['telemetrySparse', () => enc.telemetry(TELEMETRY_SPARSE)],
    ['route', () => enc.route(ROUTE)],
    ['state', () => enc.state({ transport: 'p2p-direct', viewerCount: 3, emitterLive: true })],
    ['heartbeat', () => enc.heartbeat(3_600_000)],
    ['end', () => enc.end({ reason: 'completed', detail: 'finished' })],
  ] as const)('encodes %s exactly as the golden vector', (name, build) => {
    expect(hex(build())).toBe(golden.envelopes[name]);
  });
});

describe('golden vectors — decode back to the expected domain values', () => {
  it('decodes the hello vector', () => {
    const msg = new Decoder().decode(unhex(golden.envelopes.hello));
    expect(msg).toEqual({ kind: 'hello', hello: HELLO });
  });

  it('decodes the full telemetry vector', () => {
    const msg = new Decoder(T0).decode(unhex(golden.envelopes.telemetryFull));
    if (msg.kind !== 'telemetry') throw new Error('expected telemetry');
    const m = msg.metrics;
    expect(m.seq).toBe(3600);
    expect(m.timestamp).toBe(T0 + 3_600_000);
    expect(m.position.lat).toBeCloseTo(46.6204190, 6);
    expect(m.position.lon).toBeCloseTo(6.2143550, 6);
    expect(m.heartRateBpm).toBe(151);
    expect(m.cadenceRpm).toBe(172);
    expect(m.powerW).toBe(288);
    expect(m.batteryPct).toBe(78);
    expect(m.route!.segIndex).toBe(137);
    expect(m.route!.offRoute).toBe(false);
    expect(m.route!.etaEpochMs).toBe(T0 + 4_500_000);
    expect(m.sources).toEqual(TELEMETRY_FULL.sources);
  });

  it('decodes the sparse telemetry vector with nulls preserved', () => {
    const msg = new Decoder(T0).decode(unhex(golden.envelopes.telemetrySparse));
    if (msg.kind !== 'telemetry') throw new Error('expected telemetry');
    const m = msg.metrics;
    expect(m.position.lat).toBeCloseTo(-33.8688, 6);
    expect(m.position.lon).toBeCloseTo(-151.2093, 6);
    expect(m.position.altM).toBeCloseTo(-12.5, 3);
    expect(m.position.hAccM).toBeNull();
    expect(m.speedMps).toBeNull();
    expect(m.courseDeg).toBeNull();
    expect(m.heartRateBpm).toBeNull();
    expect(m.powerW).toBeNull();
    expect(m.route).toBeNull();
    expect(m.batteryPct).toBeNull();
    expect(m.sources.heartRate).toBe('unknown');
  });

  it('decodes the route vector and reconstructs the polyline', () => {
    const msg = new Decoder(T0).decode(unhex(golden.envelopes.route));
    if (msg.kind !== 'route') throw new Error('expected route');
    expect(msg.route.name).toBe('Col de Balme');
    expect(msg.route.points).toHaveLength(ROUTE.points.length);
    ROUTE.points.forEach((p, i) => {
      expect(msg.route.points[i]!.lat).toBeCloseTo(p.lat, 6);
      expect(msg.route.points[i]!.lon).toBeCloseTo(p.lon, 6);
      expect(msg.route.points[i]!.eleM).toBeCloseTo(p.eleM, 1);
    });
  });

  it('decodes the control vectors', () => {
    const dec = new Decoder(T0);
    expect(dec.decode(unhex(golden.envelopes.state))).toEqual({
      kind: 'state',
      state: { transport: 'p2p-direct', viewerCount: 3, emitterLive: true },
    });
    expect(dec.decode(unhex(golden.envelopes.heartbeat))).toEqual({
      kind: 'heartbeat',
      tMs: 3_600_000,
    });
    expect(dec.decode(unhex(golden.envelopes.end))).toEqual({
      kind: 'end',
      end: { reason: 'completed', detail: 'finished' },
    });
  });
});

describe('golden vectors — deterministic E2EE framing', () => {
  it('produces a reproducible sealed frame from the fixed key and salt', async () => {
    const key = await importSessionKey(unhex(golden.testKeyHex));
    const sealer = FrameSealer.create(key, SESSION_ID, unhex(golden.testSaltHex));
    const frame = await sealer.seal(unhex(golden.envelopes.telemetryFull));

    // header is fully determined: version ‖ salt ‖ counter=0
    expect(hex(frame.subarray(0, 13))).toBe(`01${golden.testSaltHex}0000000000000000`);

    // and a matching opener recovers the exact envelope bytes
    const opener = FrameOpener.create(key, SESSION_ID);
    expect(hex(await opener.open(frame))).toBe(golden.envelopes.telemetryFull);
  });

  it('advances the nonce counter deterministically across frames', async () => {
    const key = await importSessionKey(unhex(golden.testKeyHex));
    const sealer = FrameSealer.create(key, SESSION_ID, unhex(golden.testSaltHex));
    for (let i = 0; i < 4; i++) {
      const frame = await sealer.seal(unhex(golden.envelopes.heartbeat));
      expect(hex(frame.subarray(5, 13))).toBe(i.toString(16).padStart(16, '0'));
    }
  });
});
